//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.FoodBooks = new HashSet<FoodBook>();
            this.RoomBooks = new HashSet<RoomBook>();
        }
    
        public string Cid { get; set; }
        public string Cname { get; set; }
        public string Cemail { get; set; }
        public Nullable<long> Cphone { get; set; }
        public string Ccity { get; set; }
        public Nullable<System.DateTime> Cdob { get; set; }
        public Nullable<int> Cpincode { get; set; }
        public string Cnation { get; set; }
        public string Cgen { get; set; }
        public string Cpass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodBook> FoodBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomBook> RoomBooks { get; set; }
    }
}
