//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBook
    {
        public int RBookid { get; set; }
        public string Cid { get; set; }
        public Nullable<int> Rid { get; set; }
        public Nullable<System.DateTime> Dfrom { get; set; }
        public Nullable<System.DateTime> Tfrom { get; set; }
        public string Rtype { get; set; }
        public Nullable<int> Rprice { get; set; }
        public Nullable<int> Pcount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Room Room { get; set; }
    }
}
